# Generated by Django 4.1.2 on 2023-11-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='OrdersId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
