# Generated by Django 4.1.2 on 2023-10-30 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('OrdersId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('DealerName', models.CharField(max_length=60)),
                ('TransporterName', models.CharField(max_length=560)),
                ('Address', models.CharField(max_length=100)),
                ('ProductName', models.CharField(max_length=60)),
                ('ProductQuantity', models.IntegerField()),
                ('DateStr', models.CharField(max_length=10)),
                ('TimeStr', models.CharField(max_length=10)),
                ('AddedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
