# Generated by Django 4.1.2 on 2023-11-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_orders_datestr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='DateStr',
            field=models.CharField(max_length=12),
        ),
    ]
